### ISSUE TITLE
Endless redirect between "oauth2/authorization/oidc?error" and "login?error""

### ISSUE THREAD

**Issue by ChristianSlupikowski** [oktadev/auth0-full-stack-java-example#7]
## Overview of the issue:
After I completed the Tutorial (https://auth0.com/blog/full-stack-java-with-react-spring-boot-and-jhipster/) to integrate Auth0 to my Application. I tried to login to the generated Application and get an endless redirection between 
"http://localhost:8080/oauth2/authorization/oidc?error"
and
"http://localhost:8080/login?error".
In the browser i get the following error:

```
"error-middleware.ts:20 authentication/get_account/rejected caught at middleware with reason: "Request failed with status code 401"."
"error-middleware.ts:23 Actual cause: error.http.401"
```

I did the exact steps, except on windows i had to set the environment variables as followed:
```
$env:SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI = 'https://???.auth0.com/'
$env:SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID = 'fsd???'
$env:SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET = 'xoO????'
$env:JHIPSTER_SECURITY_OAUTH2_AUDIENCE = 'https://???.auth0.com/api/v2/'
```

Also i had to set a connection in Auth0 to create a User:
Auth0 -> Authentification -> Database -> Username-Password-Authentication -> Applications -> Add my Application

I also tried it with this git repo and had the same thing.
Maybe there is something missing with the use of it in windows or am i missing something in the auth0 configuration?

**Motivation for or Use Case:**
The Application should be configured with Auth0.

**Reproduce the error:**
1. Clone the App from this Repository.
2. Activate the connection in Auth0 as mentioned above and configure Auth0 as described in the tutorial.
3. Instead of "source" use $env: to set the environment variables.
4. Start Application and try to login.

**Related issues**
n/a

**Suggest a Fix**
n/a

**JHipster configuration**
`jhipster info`
```
##### **JHipster Version(s)**

flickr-2@0.0.1-SNAPSHOT C:\Users\Christian\Desktop\flickr2\auth0-full-stack-java-example
-- generator-jhipster@7.4.1




##### **JHipster configuration, a .yo-rc.json file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "baseName": "flickr2",
    "jhipsterVersion": "7.3.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress"],
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1634022348068,
    "serviceDiscoveryType": "no",
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.auth0.flickr2",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "united",
    "clientThemeVariant": "dark",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "devServerPort": 9060,
    "clientPackageManager": "npm",
    "languages": ["en", "pt-br"],
    "enableGradleEnterprise": false,
    "entities": ["Album", "Photo", "Tag"],
    "lastLiquibaseTimestamp": 1634025089000,
    "herokuAppName": "flickr-2",
    "herokuDeployType": "git",
    "herokuJavaVersion": "11",
    "useOkta": false
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Album {
  title String required
  description TextBlob
  created Instant
}
entity Photo {
  title String required
  description TextBlob
  image ImageBlob required
  height Integer
  width Integer
  taken Instant
  uploaded Instant
}
entity Tag {
  name String required minlength(2)
}
relationship ManyToOne {
  Album{user(login)} to User
  Photo{album(title)} to Album
}
relationship ManyToMany {
  Photo{tag(name)} to Tag{photo}
}

paginate Album with pagination
paginate Photo, Tag with infinite-scroll

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.14" 2022-01-18
OpenJDK Runtime Environment Temurin-11.0.14+9 (build 11.0.14+9)
OpenJDK 64-Bit Server VM Temurin-11.0.14+9 (build 11.0.14+9, mixed mode)

git version 2.35.1.windows.2

node: v16.14.0

npm: 8.3.1

Docker version 20.10.12, build e91ed57

docker-compose version 1.29.2, build 5becea4c


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

JHipster configuration, a .yo-rc.json file generated in the root folder
- see this git repo

**Browsers and Operating System:**
OS: Windows 10
Powershell: 5 .1.19041.1320
Browser: Edge Version 98.0.1108.56 

- [ ]  Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I believe you have to rename `.okta.env` to `okta.bat` and use `set` instead of `export`. 

```
set SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI = 'https://???.auth0.com/'
set SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID = 'fsd???'
set SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET = 'xoO????'
set JHIPSTER_SECURITY_OAUTH2_AUDIENCE = 'https://???.auth0.com/api/v2/'
```

Then, run `okta.bat`. 

You could also change the default values in `src/main/resources/config/application.yml`. Just don't check your client secret into source control!

https://github.com/oktadev/auth0-full-stack-java-example/blob/main/src/main/resources/config/application.yml#L133

**Comment by mraible** [comment]
@ChristianSlupikowski Please reopen this issue if you're still having problems.

**Comment by ChristianSlupikowski** [comment]
The problem wasn't with the environment variables.
I tried it on a different windows PC and it worked there. I did the exact same steps.
I have to double check the installed versions and find out why this is happing.
If I find out more, i let you know.

Thanks for the Reply.
