### ISSUE TITLE
Can't upload photo - javascript error

### ISSUE THREAD

**Issue by bradparks** [oktadev/auth0-full-stack-java-example#9]
Hey! I can login and create tags, albums, photos, etc, and it seems to work great.

But when I try and save a photo, clicking on the "Save" button seems to fail silently.

Looking in the console, I see the following:
```

photo-update.tsx:47 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
    at photo-update.tsx:47:1
    at Array.find (<anonymous>)
    at saveEntity (photo-update.tsx:47:1)
    at index.cjs.js:1:1
```

which leads me to the `const entity` line below:

```
  const saveEntity = values => {
    values.taken = convertDateTimeToServer(values.taken);
    values.uploaded = convertDateTimeToServer(values.uploaded);

    const entity = {
      ...photoEntity,
      ...values,
      tags: mapIdList(values.tags),
      album: albums.find(it => it.id.toString() === values.album.toString()),
    };

```

**Comment by bradparks** [comment]
Cool - good to know - 99% FYI, but just thought I'd mention it

**Comment by mraible** [comment]
@bradparks FYI... I recreated the app with JHipster v7.7.0 and this issue doesn't happen there. I also noticed the name of the album dropdown changed between versions, so I fixed it.
